### ISSUE TITLE
Stream name supports wildcards

### ISSUE THREAD

**Issue by hanqian200705** [zinclabs/zincobserve#139]
### Description

Log query and func configuration page, stream  supports wildcards.

Query all streams starting with devlog.202302
devlog.202302*

The stream condition can be empty ，query all streams

### Proposed solution

No

### Alternatives considered

No

**Comment by hengfeiyang** [comment]
We will support `JOIN` in SQL in the future. 

But we suggest using a single stream for the same service not creating multiple streams by date. Because:
1. We store data hourly, the query data will only scan data in the request time range. 
2. We will add a data auto-expired feature. you can don't care about the old data.
3. The storage size will very small compare to ES, earlier you need to care about disk size, but for now, it will 10x lower than ES.
