### ISSUE TITLE
Searching and filtering is not working

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincobserve#402]
### Which ZincObserve functionalities are the source of the bug?

logs search

### Is this a regression?

Yes

### Description

Filters are not giving correct results.

https://www.loom.com/share/46b44138af9143f7bb629bb8896bd9d5

### Please provide a link to a minimal reproduction of the bug

https://www.loom.com/share/46b44138af9143f7bb629bb8896bd9d5

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.3.0
```

**Comment by hengfeiyang** [comment]
@prabhatsharma This is a classic problem with `NULL` in SQL. Actually you can't filter those records because there is no field `code` in those records, the real value for those records are: `code is NULL`. 

`NULL` is a special value in SQL, it does not equal anything, you can select by `select * from table where code is null`.

As your case you can do it like this:

```
SELECT * from table where code != 200 or code is null
```

**Comment by prabhatsharma** [comment]
closing as documented in https://docs.zinc.dev/user-guide/logs/example-queries/
