### ISSUE TITLE
Sharing dashboard link for duration other than 15 mins doesn't work 

### ISSUE THREAD

**Issue by oasisk** [zinclabs/zincobserve#412]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Dashboard link should also have time range as query param which helps viewing exact same data , it is missing today :http://localhost:5080/web/dashboards/view?dashboard=8516860263

### Please provide a link to a minimal reproduction of the bug

http://localhost:5080/web/dashboards/view?dashboard=8516860263

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.3.0
```

**Comment by ktx-kirtan** [comment]
@bjp232004 We might need to rearchitect the duration selection component so that it can expose the minimal data that can be used to sync with query strings

**Comment by ktx-keshavi** [comment]
We have checked on the query string architecture for the date-time component. It is currently working on based on the emits. But now we need to provide the v-model as well so that we can pass the custom values from the query strings.

We may also reduce the number of params (if possible) so that our query strings stay small and the same can be applied to logs page as well.

**Comment by gaby** [comment]
👍🏻 for fixing this. Other thing i noticed is that going between menus it always defaults to 15min

**Comment by hengfeiyang** [comment]
fixed
