### ISSUE TITLE
UI：label overlap on the x-axis

### ISSUE THREAD

**Issue by hanqian200705** [zinclabs/zincobserve#434]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

When there are too many data on the x-axis, the text may overlap and make it difficult to see clearly.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/4269408/227889839-35d6f12e-7799-4221-a85d-a8553d6049bf.png">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
v0.3.1

Commit Hash
8dd793a2c2b9e1dc30e05d0d6e3123916b800ea8

Build Date
2023-03-25T17:49:05Z
```

**Comment by ktx-keshavi** [comment]
For this, we have removed the text breaking to multiple lines as plotly doesn't handle it by itself. So, we had added the text wrapping into multiple lines to avoid long labels with automargins. So the above issue has appeared. To solve this, we have now truncated the long labels on x axis larger than 15 chars. As plotly doesn't show the full label on axis hover, we have added it to the tooltip along with the y value. This has been handled differently for horizontal bar, pie and all other charts. Attaching sample screenshots of each:

Horizontal Bar:

![image](https://user-images.githubusercontent.com/124258826/228244584-bed84e31-ef08-4ca4-8ac6-3fa3f288e393.png)

Pie: 
In pie label wrapping instead of truncate is applied as legends were too long (same behaviour as previous)
![image](https://user-images.githubusercontent.com/124258826/228245058-c6cf16a3-9a46-45d4-905e-4eebcf343da3.png)


Bar and others:

![image](https://user-images.githubusercontent.com/124258826/228244775-7f98d29c-638b-42b8-bb29-26b29c207e45.png)

**Comment by bjp232004** [comment]
is there any way to limit the number of labels? So for example, if there are thousands of records on the x-axis, so instead of showing all labels on the x-axis, can we limit the number of labels displayed on the x-axis?

Labels will be available by hovering over the "bar".

**Comment by ktx-kirtan** [comment]
We have to do it manually. As there is no automated way of doing that from plotly. But, yes we can create a logic where we can restrict the number of entries shown in the x axis. With the current implementation also we should not be having any issues as we are not showing multiline. We will check again with the chart where there too manny x axis values and if the overlapping is happening, will restrict the number of items.

**Comment by ktx-kirtan** [comment]
Labels will be there on hover always as shown in the screenshots above

**Comment by prabhatsharma** [comment]
Completed in v0.4.1
