### ISSUE TITLE
Which functions and scenarios of promql should we prioritize?

### ISSUE THREAD

**Issue by hengfeiyang** [zinclabs/zincobserve#582]
### Which ZincObserve functionalities are relevant/related to the feature request?

metrics

### Description

- [x] zo_ingest_wal_read_bytes
- [x] rate(zo_ingest_wal_read_bytes{namespace="$namespace"}[5m])
- [x] sum(irate(zo_ingest_wal_read_bytes{namespace="$namespace"}[5m])) by (pod)
- [x] sum(zo_ingest_wal_used_bytes{namespace="$namespace"}) by (pod)
- [x] max(zo_meta_storage_bytes{namespace="$namespace"})
- [x] topk(10, irate(zo_compact_used_time{namespace="$namespace"}[1m]))
- [x] topk(10, sum(zo_query_cache_files{namespace="$namespace"})by(organization,stream_type,stream))
- [x] topk(10, max(zo_storage_original_bytes{namespace="$namespace"})by(organization,stream_type,stream))
- [x] histogram_quantile(0.95, sum(irate(zo_http_response_time_bucket{namespace="$namespace"}[5m])) by (le, exported_endpoint))

**Comment by vvv** [comment]
See also [PromQL Cheat Sheet](https://promlabs.com/promql-cheat-sheet/). Maybe one of the expressions there is so useful that we'll want to implement it sooner?

**Comment by hengfeiyang** [comment]
@vvv in the Sheet, there are too many cases, i think we should choose some cases.

**Comment by hengfeiyang** [comment]
@vvv I think we can support some cases from [PromQL Cheat Sheet](https://promlabs.com/promql-cheat-sheet/).

- [x] Selecting series
- [x] Rates of increase for counters
- [x] Quantiles from histograms
- [x] Aggregating over time
- [x] Aggregating over multiple series

**Comment by syepes** [comment]
This will be a great feature, one thing that could set a good base line would be to start passing some of the **core** [compliance tests](https://promlabs.com/promql-compliance-tests/).

One other influencing project could be what the guys from VistoriaMetrics have implemented on top of the standard PromQL + [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html), they add some enhancements and additional functions this could inspire the **ZoQL** :-)


it's not 100% compliant because of some histogram and value differences, but IMHO it's not necessary to be 100% compliant we have been using MetricsQL for +4 years now and never had into issues.

**Comment by prabhatsharma** [comment]
+1 for compliance tests

**Comment by hengfeiyang** [comment]
@syepes We have done all the functions listed in this issue.
