### ISSUE TITLE
How to proceed monitor when stream is separated into multiple files by timeKey

### ISSUE THREAD

**Issue by toby1991** [zinclabs/zincobserve#767]
### Description

<img width="920" alt="image" src="https://github.com/zinclabs/zincobserve/assets/5897356/7dff8967-dd5c-4e03-8ff9-aaf1c7fb6ec8">

How to proceed this query scenario?

### Proposed solution

-

### Alternatives considered

-

**Comment by hengfeiyang** [comment]
we haven't supported queries with variables. 

And, I suggest use single stream, in ZincObserve you don't need create stream by day. 

Elasticsearch create index by day because when it query data it must load everything in the stream, you can't query a piece of data.

But in ZincObserve we queiry data with time range, we can find data in minute level, so you don't need create stream by day. just one stream, you life will easier.
